# Generated by Django 6.0.2 on 2026-02-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="priority",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("urgent", "Urgent"),
                ],
                default="info",
                max_length=10,
            ),
        ),
    ]
