# Generated by Django 6.0.2 on 2026-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_reminder_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=15)),
                ("middle_initial", models.CharField(max_length=1)),
                ("last_name", models.CharField(max_length=10)),
                (
                    "extension_name",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("contact_number", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("student_id", models.CharField(max_length=8)),
                ("course", models.CharField(max_length=100)),
                (
                    "year_level",
                    models.IntegerField(
                        choices=[
                            (1, "1st Year"),
                            (2, "2nd Year"),
                            (3, "3rd Year"),
                            (4, "4th Year"),
                        ]
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("1st", "1st Semester"), ("2nd", "2nd Semester")],
                        max_length=5,
                    ),
                ),
                (
                    "application_form",
                    models.FileField(blank=True, upload_to="applications/new/"),
                ),
                (
                    "id_picture",
                    models.ImageField(blank=True, upload_to="applications/new/"),
                ),
                (
                    "barangay_clearance",
                    models.FileField(blank=True, upload_to="applications/new/"),
                ),
                (
                    "parents_itr",
                    models.FileField(blank=True, upload_to="applications/new/"),
                ),
                (
                    "enrolment_form",
                    models.FileField(blank=True, upload_to="applications/new/"),
                ),
                (
                    "schedule_classes",
                    models.FileField(blank=True, upload_to="applications/new/"),
                ),
                (
                    "proof_insurance",
                    models.FileField(blank=True, upload_to="applications/new/"),
                ),
                (
                    "grades_last_sem",
                    models.FileField(blank=True, upload_to="applications/new/"),
                ),
                (
                    "official_time",
                    models.FileField(blank=True, upload_to="applications/new/"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
