# Generated by Django 6.0.2 on 2026-02-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_newapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="newapplication",
            name="assigned_office",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="interview_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("office_assigned", "Office Assigned"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
