# Generated by Django 6.0.2 on 2026-02-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_newapplication_assigned_office_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RenewalApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=8)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=11)),
                ("address", models.TextField()),
                ("course", models.CharField(max_length=100)),
                (
                    "year_level",
                    models.IntegerField(
                        choices=[
                            (1, "1st Year"),
                            (2, "2nd Year"),
                            (3, "3rd Year"),
                            (4, "4th Year"),
                        ]
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("1st", "1st Semester"), ("2nd", "2nd Semester")],
                        max_length=5,
                    ),
                ),
                (
                    "previous_office",
                    models.CharField(
                        choices=[
                            ("registrar", "Registrar"),
                            ("library", "Library"),
                            ("guidance", "Guidance Office"),
                            ("deans", "Dean's Office"),
                            ("cashier", "Cashier"),
                            ("osa", "Office of Student Affairs"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "preferred_office",
                    models.CharField(
                        choices=[
                            ("registrar", "Registrar"),
                            ("library", "Library"),
                            ("guidance", "Guidance Office"),
                            ("deans", "Dean's Office"),
                            ("cashier", "Cashier"),
                            ("osa", "Office of Student Affairs"),
                        ],
                        max_length=50,
                    ),
                ),
                ("hours_rendered", models.PositiveIntegerField()),
                (
                    "supervisor_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "enrolment_form",
                    models.FileField(blank=True, upload_to="applications/renewal/"),
                ),
                (
                    "schedule_classes",
                    models.FileField(blank=True, upload_to="applications/renewal/"),
                ),
                (
                    "grades_last_sem",
                    models.FileField(blank=True, upload_to="applications/renewal/"),
                ),
                (
                    "official_time",
                    models.FileField(blank=True, upload_to="applications/renewal/"),
                ),
                (
                    "recommendation_letter",
                    models.FileField(blank=True, upload_to="applications/renewal/"),
                ),
                (
                    "evaluation_form",
                    models.FileField(blank=True, upload_to="applications/renewal/"),
                ),
                ("interview_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_office",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("office_assigned", "Office Assigned"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
