# Generated by Django 6.0.2 on 2026-02-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_renewalapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("building", models.CharField(max_length=200)),
                ("room", models.CharField(blank=True, default="", max_length=200)),
                (
                    "hours",
                    models.CharField(
                        default="Mon–Fri, 8:00 AM – 5:00 PM", max_length=200
                    ),
                ),
                ("head", models.CharField(blank=True, default="", max_length=200)),
                ("total_slots", models.PositiveIntegerField(default=3)),
                ("latitude", models.FloatField(default=10.6432)),
                ("longitude", models.FloatField(default=122.9394)),
                (
                    "icon",
                    models.CharField(default="fa-solid fa-building", max_length=100),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
