# Generated by Django 6.0.2 on 2026-02-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="latitude",
            field=models.FloatField(default=10.7426),
        ),
        migrations.AlterField(
            model_name="office",
            name="longitude",
            field=models.FloatField(default=122.9703),
        ),
    ]
