# Generated by Django 6.0.2 on 2026-02-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_update_office_coords_talisay_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="newapplication",
            name="preferred_office",
            field=models.ForeignKey(
                blank=True,
                help_text="Office the student prefers to be assigned to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_applications",
                to="home.office",
            ),
        ),
        migrations.AlterField(
            model_name="renewalapplication",
            name="preferred_office",
            field=models.ForeignKey(
                blank=True,
                help_text="Office the student prefers for renewal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewal_preferred",
                to="home.office",
            ),
        ),
        migrations.AlterField(
            model_name="renewalapplication",
            name="previous_office",
            field=models.ForeignKey(
                blank=True,
                help_text="Office where the student previously served.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewal_previous",
                to="home.office",
            ),
        ),
    ]
