# Generated by Django 6.0.2 on 2026-02-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_newapplication_preferred_office_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newapplication",
            name="student_id",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="renewalapplication",
            name="student_id",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
