# Generated by Django 6.0.2 on 2026-02-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_newapplication_student_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_done", "Interview Done"),
                    ("office_assigned", "Office Assigned"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="renewalapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_done", "Interview Done"),
                    ("office_assigned", "Office Assigned"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
