# Generated by Django 6.0.2 on 2026-02-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_newapplication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="renewalapplication",
            name="id_picture",
            field=models.ImageField(blank=True, upload_to="applications/renewal/"),
        ),
    ]
