# Generated by Django 6.0.2 on 2026-02-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_renewalapplication_id_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="expires_at",
            field=models.DateField(
                blank=True,
                help_text="Content will hide from homepage after this date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="expires_at",
            field=models.DateField(
                blank=True,
                help_text="Content will hide from homepage after this date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="upcomingdate",
            name="expires_at",
            field=models.DateField(
                blank=True,
                help_text="Content will hide from homepage after this date.",
                null=True,
            ),
        ),
    ]
