# Generated by Django 6.0.2 on 2026-03-03 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_activestudentassistant_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="newapplication",
            name="availability_schedule",
            field=models.JSONField(
                blank=True,
                help_text='Student available days/time slots as {"Monday": ["8:00 AM - 9:00 AM", ...], ...}',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="director_notes",
            field=models.TextField(
                blank=True, default="", help_text="Internal notes from director."
            ),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="requested_documents_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description of which additional documents are needed from the student.",
            ),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="schedule_mismatch_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Staff note explaining schedule mismatch.",
            ),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="schedule_verified",
            field=models.BooleanField(
                default=False,
                help_text="Staff has verified schedule matches uploaded Schedule of Classes.",
            ),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="staff_notes",
            field=models.TextField(
                blank=True, default="", help_text="Internal notes from staff."
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="availability_schedule",
            field=models.JSONField(
                blank=True,
                help_text='Student available days/time slots as {"Monday": ["8:00 AM - 9:00 AM", ...], ...}',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="director_notes",
            field=models.TextField(
                blank=True, default="", help_text="Internal notes from director."
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="requested_documents_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description of which additional documents are needed from the student.",
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="schedule_mismatch_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Staff note explaining schedule mismatch.",
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="schedule_verified",
            field=models.BooleanField(
                default=False,
                help_text="Staff has verified schedule matches uploaded Schedule of Classes.",
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="staff_notes",
            field=models.TextField(
                blank=True, default="", help_text="Internal notes from staff."
            ),
        ),
        migrations.AlterField(
            model_name="newapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("schedule_mismatch", "Schedule Mismatch — Re-input Required"),
                    ("documents_requested", "Additional Documents Requested"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_done", "Interview Done"),
                    ("office_assigned", "Office Assigned"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="renewalapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("schedule_mismatch", "Schedule Mismatch — Re-input Required"),
                    ("documents_requested", "Additional Documents Requested"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_done", "Interview Done"),
                    ("office_assigned", "Office Assigned"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("staff", "Staff Note"),
                            ("director", "Director Note"),
                            ("schedule_mismatch", "Schedule Mismatch"),
                            ("document_request", "Document Request"),
                            ("status_change", "Status Change"),
                        ],
                        default="staff",
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_log",
                        to="home.newapplication",
                    ),
                ),
                (
                    "renewal_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_log",
                        to="home.renewalapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
