# Generated by Django 6.0.2 on 2026-03-05 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_newapplication_availability_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newapplication",
            name="student_id",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "Student ID must be exactly 8 digits."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="renewalapplication",
            name="student_id",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "Student ID must be exactly 8 digits."
                    ),
                ],
            ),
        ),
    ]
