# Generated by Django 6.0.2 on 2026-03-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_remove_studentprofile_application_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="activestudentassistant",
            name="duty_schedule",
            field=models.JSONField(
                blank=True,
                help_text='Duty time slots as {"Monday": ["8:00 AM - 9:00 AM", ...], ...}',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="shift",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Time slot label, e.g. "8:00 AM - 9:00 AM"',
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("student_assistant", "date", "shift")},
        ),
    ]
