# Generated by Django 6.0.2 on 2026-03-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_attendancerecord_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newapplication",
            name="returned_documents",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-document return reasons, e.g. {"id_picture": "Photo is blurry"}',
            ),
        ),
        migrations.AddField(
            model_name="renewalapplication",
            name="returned_documents",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-document return reasons, e.g. {"id_picture": "Photo is blurry"}',
            ),
        ),
    ]
