# Generated by Django 6.0.2 on 2026-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_performanceevaluation_recommendation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500, unique=True)),
                ("data", models.BinaryField()),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Database File",
                "verbose_name_plural": "Database Files",
            },
        ),
    ]
