"""
Django settings for student_application project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3sy5%^@irja8y&j4i*)jf)(+#=p_n@e_o7!19%-l2-gws_980c"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://*.devtunnels.ms",
    "https://*.vscode.dev",
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "home",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "student_application.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "student_application.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "student_assistant_db",
        "USER": "postgres",
        "PASSWORD": "1234",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = []

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ── Encrypted Data Storage (Fernet symmetric encryption for backups) ──
DATA_ENCRYPTION_KEY = "WAQ0AyjYw1kuHp2Xhr6-VKtyUO1NZPyPOLF0CJuiKLY="

# Authentication
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Session — expire on browser close + 30 min inactivity
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_SAVE_EVERY_REQUEST = True

# ── Email Configuration ──
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "jtcoronel.chmsu@gmail.com"
EMAIL_HOST_PASSWORD = "niybahwlsjezqobf"
DEFAULT_FROM_EMAIL = "SWA Application System <jtcoronel.chmsu@gmail.com>"

# ══════════════════════════════════════════════════════════════
#  Django Jazzmin — Admin Panel Configuration
# ══════════════════════════════════════════════════════════════

JAZZMIN_SETTINGS = {
    # ── Window / Tab title ──
    "site_title": "SWA Admin",
    "site_header": "SWA Application System",
    "site_brand": "SWA Admin",
    "site_logo": None,
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to SWA Application System",
    "copyright": "Carlos Hilado Memorial State University",

    # ── Search bar ──
    "search_model": ["auth.User", "home.NewApplication", "home.RenewalApplication"],

    # ── Top Menu (navbar links) ──
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Student Site", "url": "/", "new_window": True},
        {"name": "Staff Dashboard", "url": "/staff/", "new_window": True},
        {"name": "Director Dashboard", "url": "/director/", "new_window": True},
        {"model": "auth.User"},
    ],

    # ── Side Menu ──
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
        "home.NewApplication",
        "home.RenewalApplication",
        "home.ActiveStudentAssistant",
        "home.AttendanceRecord",
        "home.PerformanceEvaluation",
        "home.Office",
        "home.StudentProfile",
        "home.Announcement",
        "home.Reminder",
        "home.UpcomingDate",
        "home.ApplicationNote",
        "home.NoDutyDay",
    ],

    # ── Icons (Font Awesome 5) ──
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "home.NewApplication": "fas fa-file-alt",
        "home.RenewalApplication": "fas fa-redo-alt",
        "home.ActiveStudentAssistant": "fas fa-user-graduate",
        "home.AttendanceRecord": "fas fa-clipboard-check",
        "home.PerformanceEvaluation": "fas fa-star-half-alt",
        "home.Office": "fas fa-building",
        "home.StudentProfile": "fas fa-id-card",
        "home.Document": "fas fa-file-upload",
        "home.ApplicationStep": "fas fa-tasks",
        "home.Announcement": "fas fa-bullhorn",
        "home.Reminder": "fas fa-bell",
        "home.UpcomingDate": "fas fa-calendar-alt",
        "home.ApplicationNote": "fas fa-sticky-note",
        "home.NoDutyDay": "fas fa-calendar-times",
        "home.DutyReminder": "fas fa-clock",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ── Related Modal ──
    "related_modal_active": True,

    # ── Custom CSS/JS ──
    "custom_css": "home/css/admin_animations.css",
    "custom_js": None,

    # ── Misc ──
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
